#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 of all active IPv4 IPs

# Update Nginx configuration to listen on port 80
sudo sed -i '/listen 80 default_server;/c\    listen 80 default_server;' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
