#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

# Install Nginx if not already installed
apt-get update
apt-get -y install nginx

# Modify Nginx configuration to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart

