#!/usr/bin/env bash
# This script configures Nginx to listen on port 80
apt-get update
apt-get -y install nginx
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
/etc/init.d/nginx restart

